import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

export interface ThemePreset {
  name: string;
  label: string;
  colors: Record<string, string>;
}

export const themePresets: ThemePreset[] = [
  {
    name: 'warm-coral',
    label: '暖珊瑚',
    colors: {
      '--color-primary': '#cc785c',
      '--color-primary-active': '#a9583e',
      '--color-primary-disabled': '#e6dfd8',
      '--color-accent': '#B85C38',
      '--color-accent-light': '#D4845E',
      '--color-accent-muted': 'rgba(184, 92, 56, 0.08)',
      '--color-accent-subtle': 'rgba(184, 92, 56, 0.04)',
      '--color-accent-teal': '#5db8a6',
      '--color-accent-amber': '#e8a55a',
      '--color-success': '#5db872',
      '--color-warning': '#d4a017',
      '--color-error': '#c64545',
      '--color-bg': '#FAF6F0',
      '--color-bg-warm': '#F5EFE6',
      '--color-canvas': '#faf9f5',
      '--color-surface': '#FFFFFF',
      '--color-surface-alt': '#F0EBE3',
      '--color-surface-soft': '#f5f0e8',
      '--color-surface-card': '#efe9de',
      '--color-surface-cream-strong': '#e8e0d2',
      '--color-border': '#E2DDD5',
      '--color-border-light': '#EDE9E2',
      '--color-hairline': '#e6dfd8',
      '--color-hairline-soft': '#ebe6df',
      '--color-tag-bg': '#EDE7DF',
      '--color-tag-text': '#6B6560',
      '--color-pos-bg': '#F7F2EB',
      '--color-pos-border': '#DDD6CC',
      '--color-exam-line': '#C9B99A',
      '--color-phonetic': '#7A6E63',
    },
  },
  {
    name: 'ocean-blue',
    label: '深海蓝',
    colors: {
      '--color-primary': '#5b8fbf',
      '--color-primary-active': '#3d6d9b',
      '--color-primary-disabled': '#d8e2ed',
      '--color-accent': '#3d6d9b',
      '--color-accent-light': '#7aaddb',
      '--color-accent-muted': 'rgba(61, 109, 155, 0.08)',
      '--color-accent-subtle': 'rgba(61, 109, 155, 0.04)',
      '--color-accent-teal': '#5db8a6',
      '--color-accent-amber': '#e8a55a',
      '--color-success': '#5db872',
      '--color-warning': '#d4a017',
      '--color-error': '#c64545',
      '--color-bg': '#F4F7FA',
      '--color-bg-warm': '#EBF0F5',
      '--color-canvas': '#f5f7fa',
      '--color-surface': '#FFFFFF',
      '--color-surface-alt': '#EBF0F5',
      '--color-surface-soft': '#f0f4f8',
      '--color-surface-card': '#e8edf3',
      '--color-surface-cream-strong': '#dce3eb',
      '--color-border': '#D5DEE5',
      '--color-border-light': '#E5EBF0',
      '--color-hairline': '#dfe5eb',
      '--color-hairline-soft': '#e8edf2',
      '--color-tag-bg': '#E5EBF2',
      '--color-tag-text': '#5E6873',
      '--color-pos-bg': '#F0F4F8',
      '--color-pos-border': '#D5DDE5',
      '--color-exam-line': '#B5C4D4',
      '--color-phonetic': '#6E7882',
    },
  },
  {
    name: 'forest-green',
    label: '森林绿',
    colors: {
      '--color-primary': '#6b9b6e',
      '--color-primary-active': '#4d7a50',
      '--color-primary-disabled': '#dae5db',
      '--color-accent': '#4d7a50',
      '--color-accent-light': '#8cba8f',
      '--color-accent-muted': 'rgba(77, 122, 80, 0.08)',
      '--color-accent-subtle': 'rgba(77, 122, 80, 0.04)',
      '--color-accent-teal': '#5db8a6',
      '--color-accent-amber': '#e8a55a',
      '--color-success': '#5db872',
      '--color-warning': '#d4a017',
      '--color-error': '#c64545',
      '--color-bg': '#F5F8F4',
      '--color-bg-warm': '#EDF2EB',
      '--color-canvas': '#f6f8f5',
      '--color-surface': '#FFFFFF',
      '--color-surface-alt': '#EDF2EB',
      '--color-surface-soft': '#f1f5ef',
      '--color-surface-card': '#e6ede4',
      '--color-surface-cream-strong': '#dae3d8',
      '--color-border': '#D5DFD4',
      '--color-border-light': '#E5EDE4',
      '--color-hairline': '#dee4db',
      '--color-hairline-soft': '#e7ede5',
      '--color-tag-bg': '#E5EDE3',
      '--color-tag-text': '#5E6B5D',
      '--color-pos-bg': '#F1F5EF',
      '--color-pos-border': '#D5DED3',
      '--color-exam-line': '#B5C4B2',
      '--color-phonetic': '#6E7A6C',
    },
  },
  {
    name: 'royal-purple',
    label: '皇家紫',
    colors: {
      '--color-primary': '#8b7ec8',
      '--color-primary-active': '#6a5da5',
      '--color-primary-disabled': '#e2def0',
      '--color-accent': '#6a5da5',
      '--color-accent-light': '#a89bdd',
      '--color-accent-muted': 'rgba(106, 93, 165, 0.08)',
      '--color-accent-subtle': 'rgba(106, 93, 165, 0.04)',
      '--color-accent-teal': '#5db8a6',
      '--color-accent-amber': '#e8a55a',
      '--color-success': '#5db872',
      '--color-warning': '#d4a017',
      '--color-error': '#c64545',
      '--color-bg': '#F8F7FB',
      '--color-bg-warm': '#F0EEF6',
      '--color-canvas': '#f8f7fb',
      '--color-surface': '#FFFFFF',
      '--color-surface-alt': '#F0EEF6',
      '--color-surface-soft': '#f3f2f8',
      '--color-surface-card': '#eae7f2',
      '--color-surface-cream-strong': '#ded9eb',
      '--color-border': '#D9D4E6',
      '--color-border-light': '#E9E6F2',
      '--color-hairline': '#e2deeb',
      '--color-hairline-soft': '#ebe7f2',
      '--color-tag-bg': '#E9E6F2',
      '--color-tag-text': '#656073',
      '--color-pos-bg': '#F3F1F8',
      '--color-pos-border': '#D9D4E5',
      '--color-exam-line': '#BFB8D4',
      '--color-phonetic': '#726E80',
    },
  },
  {
    name: 'sunset-rose',
    label: '日落玫瑰',
    colors: {
      '--color-primary': '#d4787c',
      '--color-primary-active': '#b8555a',
      '--color-primary-disabled': '#eedade',
      '--color-accent': '#b8555a',
      '--color-accent-light': '#e89b9e',
      '--color-accent-muted': 'rgba(184, 85, 90, 0.08)',
      '--color-accent-subtle': 'rgba(184, 85, 90, 0.04)',
      '--color-accent-teal': '#5db8a6',
      '--color-accent-amber': '#e8a55a',
      '--color-success': '#5db872',
      '--color-warning': '#d4a017',
      '--color-error': '#c64545',
      '--color-bg': '#FBF7F6',
      '--color-bg-warm': '#F5EDEC',
      '--color-canvas': '#faf7f6',
      '--color-surface': '#FFFFFF',
      '--color-surface-alt': '#F5EDEC',
      '--color-surface-soft': '#f7f2f1',
      '--color-surface-card': '#efe7e6',
      '--color-surface-cream-strong': '#e5dbd9',
      '--color-border': '#E2D9D7',
      '--color-border-light': '#EDE7E5',
      '--color-hairline': '#e6dedc',
      '--color-hairline-soft': '#ebe5e3',
      '--color-tag-bg': '#EDE7E5',
      '--color-tag-text': '#6B6362',
      '--color-pos-bg': '#F7F2F1',
      '--color-pos-border': '#DDD5D3',
      '--color-exam-line': '#C9BDBB',
      '--color-phonetic': '#7A706F',
    },
  },
  {
    name: 'midnight-slate',
    label: '暗夜灰',
    colors: {
      '--color-primary': '#7b8c9e',
      '--color-primary-active': '#5a6b7d',
      '--color-primary-disabled': '#dfe3e7',
      '--color-accent': '#5a6b7d',
      '--color-accent-light': '#9babb8',
      '--color-accent-muted': 'rgba(90, 107, 125, 0.08)',
      '--color-accent-subtle': 'rgba(90, 107, 125, 0.04)',
      '--color-accent-teal': '#5db8a6',
      '--color-accent-amber': '#e8a55a',
      '--color-success': '#5db872',
      '--color-warning': '#d4a017',
      '--color-error': '#c64545',
      '--color-bg': '#F7F8F9',
      '--color-bg-warm': '#EEF0F2',
      '--color-canvas': '#f7f8f9',
      '--color-surface': '#FFFFFF',
      '--color-surface-alt': '#EEF0F2',
      '--color-surface-soft': '#f2f4f5',
      '--color-surface-card': '#e8eaec',
      '--color-surface-cream-strong': '#dce0e3',
      '--color-border': '#D5D9DD',
      '--color-border-light': '#E6E9EC',
      '--color-hairline': '#dfe3e6',
      '--color-hairline-soft': '#e8ebee',
      '--color-tag-bg': '#E6E9EC',
      '--color-tag-text': '#5E6368',
      '--color-pos-bg': '#F2F4F5',
      '--color-pos-border': '#D5D9DC',
      '--color-exam-line': '#B5BCC3',
      '--color-phonetic': '#6E7378',
    },
  },
];

const DEFAULT_THEME = 'warm-coral';

const useThemeStore = defineStore('themeStore', () => {
  const activeTheme = ref<string>(DEFAULT_THEME);

  const currentPreset = computed(() =>
    themePresets.find((p) => p.name === activeTheme.value) ?? themePresets[0]!,
  );

  const setTheme = (name: string) => {
    if (themePresets.some((p) => p.name === name)) {
      activeTheme.value = name;
    }
  };

  return {
    activeTheme,
    currentPreset,
    setTheme,
  };
}, { persist: true });

export { useThemeStore };
